name: NanoProject
version: '1.0-SNAPSHOT'
main: org.pspkk.nanoproject.NanoProject
api-version: '1.21'
commands:
  ZB:
    description: "baby"
    usage: "/ZB [W...What]"
    aliases: [nanoproject]
    permission: nanoproject.command.ZB
    permission-message: "You do not have permission"

